In [ ]:
from rpy2.robjects import default_converter
from rpy2.robjects import pandas2ri
from rpy2.robjects.conversion import localconverter

# use the default conversion rules to which the pandas conversion
# is added
with localconverter(default_converter + pandas2ri.converter) as cv:
    dataf = robjects.r["https://github.com/cran/bayesm/blob/master/data/customerSat.rda"]

In [1]:
import pandas as pd
import numpy as np
import edward as ed
import tensorflow as tf

In [2]:
data = pd.read_csv("/Users/hauptjoh/Downloads/customerSat.csv")

In [4]:
data.columns

Index(['q1', 'q2', 'q3', 'q4', 'q5', 'q6', 'q7', 'q8', 'q9', 'q10'], dtype='object')

In [7]:
data[0:10]

   q1  q2  q3  q4  q5  q6  q7  q8  q9  q10
0   2   8   8   2   2   2   2   6   8    6
1   7   8   8   8   7   6   8   9   8   10
2   5   3   3   2   3   5   4   4   7    7
3   8   7   6   7   8   8   8   8   8    8
4   2   1   1   1   1   1  10   2  10    8
5   7   8   8   4   5   6   8   8  10   10
6  10  10  10  10  10  10  10  10  10   10
7   7   8   8   5   7   7   7   8   5    7
8   5   5   6   4   4   7   6   4   9    9
9   1   2   3   2   1   1   1   5  10   10